default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: kbase
  username: admin
  password: admin
  host: localhost
  port: 5432

test:
  <<: *default
  database: kbase_test

production:
  <<: *default
  database: <%= ENV['DATABASE_URL'] %>
